VidlyAps.netMVC/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VidlyAps.netMVC.Models;

namespace VidlyAps.netMVC.Controllers
{
    public class MoviesController : Controller
    {
        private ApplicationDbContext db;

        public MoviesController()
        {
            db = new ApplicationDbContext();
        }
        // GET: Movies
        public ActionResult Index()
        {
            var movies = db.Movies.Include(m=>m.Genre).ToList();
            return View(movies);
        }
        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            var movies = db.Movies.Include(m => m.Genre).SingleOrDefault(c => c.Id == id);
            if (movies == null)
                return HttpNotFound();
            return View(movies);
        }

    }
}

VidlyAps.netMVC/Views/Movies/Details.cshtml
@model VidlyAps.netMVC.Models.Movie

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<p>Genre: @Model.Genre.Name</p>
<p>Created  Date: @Model.CreatedDate</p>
<p>Last Modidfied: @Model.UpdateDate</p>
<p>Number of stock: @Model.Stocks</p>

VidlyAps.netMVC/Views/Movies/Index.cshtml
@model IEnumerable<VidlyAps.netMVC.Models.Movie>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>

@if (Model.Any())
{
<table class="table table-bordered table-hover">
    <thead>
       <tr>
           <td>Movies</td>
           <td>Genre</td>
       </tr>
    </thead>
    <tbody>
        @foreach (var movie in Model)
        {
            <tr>
                <td>@Html.ActionLink(movie.Name, "Details", "Movies", new { id = movie.Id }, new { })</td>
                <td>@movie.Genre.Name</td>
            </tr>
            

        }
    </tbody>
</table>
}
else { 

   <p>Sorry Doesnot have any movies</p>

}